version: '3.7'
services:
  php:
    image: registry.gitlab.com/floor12/images:basic80
    networks:
      - example
    deploy:
      replicas: 3
      mode: replicated
  nginx:
    image: nginx
    configs:
      - source: nginx_config
        target: /etc/nginx/conf.d/default.conf
    ports:
      - '8888:80'
    networks:
      - example
    deploy:
      replicas: 1
      mode: replicated
configs:
  nginx_config:
    file: ./app.conf
networks:
  example:
    driver: overlay
    driver_opts:
      encrypted: "true"